version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: FKNDetector
      POSTGRES_USER: rout
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: trueShiel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
