# Utiliza la imagen base de PostgreSQL
FROM postgres:latest

# Variables de entorno para configurar la base de datos
ENV POSTGRES_DB=FKNDetector
ENV POSTGRES_USER=rout

# Exponer el puerto 5432
EXPOSE 5432

# Volumen para almacenar los datos de la base de datos
VOLUME ["/var/lib/postgresql/data"]
