version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rout
      POSTGRES_USER: rout
      POSTGRES_PASSWORD: rout
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: oruz2019@gmail.com
      PGADMIN_DEFAULT_PASSWORD: cdap0901
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
