# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set image tag with timestamp
        id: set_tag
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo $DOCKER_TOKEN | docker login --username cdapdev2020 --password-stdin
      
      - name: Build images
        run: |
          cd manager-server
          docker build -t cdapdev2020/dj-manager-server:${{ env.IMAGE_TAG }} .
          cd ..
          cd rss-api
          docker build -t cdapdev2020/rss-api:${{ env.IMAGE_TAG }} .
          cd ..
          cd angular-client
          docker build -t cdapdev2020/angular-clinet:${{ env.IMAGE_TAG }} .


      - name: Push image
        run: |
          docker push cdapdev2020/dj-manager-server:${{ env.IMAGE_TAG }}
          docker push cdapdev2020/rss-api:${{ env.IMAGE_TAG }}
          docker push cdapdev2020/angular-clinet:${{ env.IMAGE_TAG }}
